- hosts: localhost
  tags: always
  become: false
  no_log: true
  pre_tasks:
    - import_tasks: Pre-Tasks/whoami.yml
    - import_tasks: Pre-Tasks/whoami_debug.yml
    - import_tasks: Pre-Tasks/temp_pass.yml
    - import_tasks: Pre-Tasks/update_packages.yml
    - import_tasks: Pre-Tasks/dependencies.yml

  roles:
    - role: base
      tags: base

    - role: workstation
      tags: workstation
      when: Setup == "1"

    - role: server
      tags: server
      when: Setup == "2"

    - role: dotfiles
      tags: dotfiles
  tasks:
    - import_tasks: Post-Tasks/enabling_default.yml
    - import_tasks: Post-Tasks/temp_remove.yml