- name: Workstation | hyprland | Remove Unwanted Packages
  block:
    - name: Workstation | hyprland | Remove fish conf
      file:
        path: ~/.config/fish
        state: absent
    - name: Workstation | hyprland | Remove foot conf
      file:
        path: ~/.config/foot
        state: absent
