- name: Workstation | hyprland | Remove Unwanted Packages
  block:
    - name: Workstation | hyprland | Remove illogical-impulse-fonts-themes
      become: true
      pacman:
        state: absent
        name: illogical-impulse-fonts-themes

    - name: Workstation | hyprland | Remove fish and foot
      become: true
      pacman:
        state: absent
        name:
          - foot
          - fish

    - name: Workstation | hyprland | Remove fish conf
      file:
        path: ~/.config/fish
        state: absent
    - name: Workstation | hyprland | Remove foot conf
      file:
        path: ~/.config/foot
        state: absent
