- name: Workstation | hyprland | Remove Unwanted Files
  block:
    - name: Workstation | hyprland | Remove illogical-impulse-fonts-themes
      become: true
      pacman: 
        state: absent
        name: illogical-impulse-fonts-themes
        
    - name: Workstation | hyprland | Remove fish and foot
      become: true
      pacman: 
        state: absent
        name: 
          - foot
          - fish

    - name: Workstation | hyprland | Remove hypr config
      file:
        path: ~/.config/hypr
        state: absent
    - name: Workstation | hyprland | Remove fish config
      file:
        path: ~/.config/fish
        state: absent
    - name: Workstation | hyprland | Remove starship.toml
      file:
        path: ~/.config/starship.toml
        state: absent
    - name: Workstation | hyprland | Remove zshrc.d
      file:
        path: ~/.config/zshrc.d
        state: absent