- name: Workstation | hyprland | Remove Unwanted Files
  block:
    - name: Workstation | hyprland | Remove hypr config
      file:
        path: ~/.config/hypr
        state: absent
    - name: Workstation | hyprland | Remove ags config
      file:
        path: ~/.config/ags
        state: absent
    - name: Workstation | hyprland | Remove fish config
      file:
        path: ~/.config/fish
        state: absent
    - name: Workstation | hyprland | Remove starship.toml
      file:
        path: ~/.config/starship.toml
        state: absent
    - name: Workstation | hyprland | Remove zshrc.d
      file:
        path: ~/.config/zshrc.d
        state: absent

#files I want to Remove

# /hypr/
# nautlilus