- name: Dotfiles | Base | zsh dotfiles
  tags: zsh,dotfiles
  become: false
  shell:
    cmd: "stow zsh"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Dotfiles | Base | nvim dotfiles
  become: false
  shell:
    cmd: "stow nvim"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Dotfiles | Base | fastfetch dotfiles
  become: false
  shell:
    cmd: "stow fastfetch"
    chdir: "{{ user_dir }}/.dotfiles/"