- name: Dotfiles | Clone Dotfiles Repo
  tags: dotfiles
  git:
    repo: https://github.com/TriforceGB/.dotfiles.git
    dest: "~/.dotfiles"
    clone: yes
    update: yes
    force: yes

- name: Dotfiles | Create .config
  file:
    path: "{{user_dir}}/.config"
    state: directory
    mode: "0755"
- import_tasks: base_dots.yml
- import_tasks: workstation_dots.yml
  when: Setup == "1"
- import_tasks: server_dots.yml
  when: Setup == "2"
