- name: Dotfiles | Workstation | hypr dotfiles
  become: false
  shell:
    cmd: "stow hypr"
    chdir: "{{ user_dir }}/.dotfiles/"
- name: Dotfiles | Workstation | kitty dotfiles
  become: false
  shell:
    cmd: "stow kitty"
    chdir: "{{ user_dir }}/.dotfiles/"
- name: Dotfiles | Workstation | fuzzel dotfiles
  become: false
  shell:
    cmd: "stow fuzzel"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Dotfiles | Workstation | Spotify dotfiles
  become: false
  shell:
    cmd: "stow spotify"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Dotfiles | Workstation | zed dotfiles
  become: false
  shell:
    cmd: "stow zed"
    chdir: "{{ user_dir }}/.dotfiles/"
