- name: Workstation | Packages | Pacman Workstation Packages Install
  become: true
  pacman:
    name:
      # Workstations Needs
      - kitty
      - firefox # backup for Browser
      - gnome-disk-utility
      - timeshift
      # Boot
      - grub
      - sddm
      - qt6
      - qt6-svg
      - qt6-virtualkeyboard
      - qt6-multimedia
      - qt6-multimedia-ffmpeg
      # Nautilus Extensions
      - nautilus
      - sushi
      - nautilus-image-converter
      - imagemagick
      # Editor and Viewer
      - audacity
      - gimp
      - gnome-text-editor
      - mission-center # Task Manager
      - libreoffice-fresh
      - loupe
      - obs-studio
      - vlc
      - zed
      # Password Manager
      - fuzzel
      - rbw
      - rofi-rbw
      # Gaming
      - steam
      - lutris
      - prismlauncher
      # Others
      - obsidian
      - syncthing
      - qbittorrent
      - vulkan-tools
      - qalculate-gtk

- name: Workstation | Packages | yay Workstation Packages Install
  become: false
  yay:
    name:
      # Workstations Needs
      - zen-browser-bin
      - vesktop-bin
      # Nautilus Extensions
      - folder-color-nautilus
      - nautilus-open-any-terminal
      # Editor and Viewer
      - visual-studio-code-bin
      # Password Manager
      - bitwarden-bin
      # Gaming
      - wootomation-appimage
      # Music
      - spotify
      - spicetify-cli
      # Other
      - archlinux-tweak-tool-git
      - localsend
# vm stuff
# emulators
# 3d printer stuff
# https://openrazer.github.io/#features
# https://polychromatic.app/features/
