- name: Base | SSH | Create .ssh
  tags: ssh
  file:
    path: "{{user_dir}}/.ssh"
    state: directory
    mode: "0700"

- name: Base | SSH | Generate Keys
  become: false
  tags: ssh
  community.crypto.openssh_keypair:
    path: "{{user_dir}}/.ssh/id_ssh_rsa"
    comment: "{{ username }}@{{ hostname }}"

- name: Base | SSH | enable sshd
  become: true
  tags: ssh
  service:
    name: sshd.service
    state: started
    enabled: yes
# - name: Base | SSH | Copy Public Key #Change this ? use bitwardden
#   become: false
#   tags: ssh
#   ansible.posix.authorized_key:
#     user: "{{ username }}"
#     state: present
#     key: '{{ item }}'
#   with_file:
#     - ssh_key/zach-desktop
#     - ssh_key/zach-vivobook
#     - ssh_key/ubuntu-homeserver
